### ISSUE TITLE
Nuget package dependencies incorrectly versioned producing build warnings in consumers

### ISSUE THREAD

**Issue by DaveAurionix** [ASOS/SimpleEventStore#20] opened 2017-09-21 08:43 UTC
Apologies for the issue with no PR - mostly logging till have time to address it...

The Asos.SimpleEventStore.DocumentDb nuget package published by the build process contains a hard reference to a Asos.SimpleEventStore package with version 1.0.0 despite the actual build taking place against a later (non-backwards-compatible) package version (e.g. 2.X.X).  This produces the following example warning in consumers using VS2017.3.4 or later:

"Asos.SimpleEventStore.AzureDocumentDb 2.0.31 depends on Asos.SimpleEventStore (>=1.0.0) but Asos.SimpleEventStore 1.0.0 was not found.  An approximate best match of Asos.SimpleEventStore 2.0.30 was resolved".

This might stop "warnings as errors" being enabled for builds.

A temporary hack might be to simple change the Version property in the csproj files to match the version of any currently published package, but although that will remove the warning, I worry that this will simply mask the issue and might result in consumers who use "minimum matching package" dependency behaviour rarely picking up new dependent package versions (i.e. those that reference SES.DocDb will not update to latest versions of SES itself).

A better approach might be to use "$" build variables in the csproj files Version elements in order to create correctly-versioned references when msbuild is spidering project references to generate the package manifest.

**Comment by DaveAurionix** [comment] 2017-09-21 08:46
[Test, please ignore] Please tell me <a href="javascript:alert('please fail')">this link</a> doesn't actually let me inject JavaScript?

**Comment by DaveAurionix** [comment] 2017-09-22 08:05
Not sure this is fixed?  If you expand the Dependencies on https://www.nuget.org/packages/Asos.SimpleEventStore.AzureDocumentDb/ it still shows a dependency on the hard-coded 1.0.0 version of Asos.SimpleEventStore, rather than the version actually required/referenced at build time.

**Comment by DaveAurionix** [comment] 2017-09-22 08:07
The issue is when msbuild spiders the csproj dependencies (say B, C) of the csproj (A) that it is packaging.  Those spidered dependencies have a <Version>1.0.0</Version> inside the B and C csproj files that is not affected by the /p:Version build parameter.  That build parameter only affects the csproj currently being built (A in this example).

**Comment by asosMikeGore** [comment] 2017-09-22 08:35
Yes it's not.  Noticed an issue with the build script tweak I did that I've just pushed out too.  Will look at this again shortly.

**Comment by asosMikeGore** [comment] 2017-09-22 09:47
The issue is to do with the MSBuild version that is on our CI/CD server.  Looking to get this updated.  Even if you override the PackageVersion param as shown in the commit above, it still defaults to 1.0.0 on the build server.

**Comment by asosMikeGore** [comment] 2017-10-23 09:12
This has just been fixed in package versions 2.0.58.  It's indexing on nuget.org at the moment so you may not see it for a few mins.

**Closed by asosMikeGore** 2017-10-23 09:12 UTC
Labels: bug
